### ISSUE TITLE
Problems with PPP

### ISSUE THREAD

**Issue by dukesun99** [CS2103-AY1819S2-W10-3/main#104]
Hi guys,

I checked the PRs related to update PPP, I found the following issues:

@e0191632 , the link in AboutUs should link to the built ".html" in gh-pages but not ".adoc"
@bendymochi and @LiuXuanIan , please link you PPP to AboutUs page also. Thanks.

I also noticed the User Guild do not have tags for each session, so when you include there might be some errors. You need to add a tag for the session you want to include before you use the tag.

**Comment by bendymochi** [comment]
Noted! Will do so about PPP. Thanks!
